# -*- coding: utf-8 -*-
"""StatisticAnalysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uaeJA7pwdT9FBHFdwj5ROMJvKukqMUQd
"""

import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from collections import Counter

!gdown 1atCLghrXBGz7D_fqhVtEmo9jeL304ogW
data = pd.read_csv("universitas_brawijaya_scholar_results2.csv")

data["word_count"] = data["Title"].apply(lambda x: len(x.split()))
data["char_count"] = data["Title"].apply(len)
print(data.describe())

all_text = " ".join(data["Title"])
word_freq = Counter(all_text.split())

plt.figure(figsize=(8, 5))
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(all_text)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title("Word Cloud dari Judul Artikel")
plt.show()
# plt.savefig("Output Diagram/Word_Cloud.png")
plt.close()

plt.figure(figsize=(10, 5))
most_common_words = dict(word_freq.most_common(10))  # Ambil 10 kata paling umum
plt.bar(most_common_words.keys(), most_common_words.values(), color='skyblue')
plt.xlabel("Kata")
plt.ylabel("Frekuensi")
plt.title("Distribusi Kata dalam Judul Artikel")
plt.xticks(rotation=45)
plt.show()
# plt.savefig("Output Diagram/Word_Distribution.png")
plt.close()